add sorting functionality
captainread/fe-nc-games pull request #7
Opened 2022-12-08 16:11 UTC by captainread

drop down for sorting type, radio buttons for asc/desc

2022-12-08 16:36 UTC, HannahBurks requested changes
Great work Alice! It looks really good so far 😄 Once the requested changes have been made, please send another PR.

2022-12-08 16:36 UTC, HannahBurks commented on src/components/Reviews.jsx
> +          <FormControl fullWidth>
 We want to make sure that reviews are sorted by default to **date** **descending** - so we may want the drop down to default to those upon loading the page.

2022-12-08 16:36 UTC, HannahBurks commented on src/components/Reviews.jsx
> +          <RadioGroup row defaultValue="desc">
This sorting feature is great, but we also want to make sure that it works for both all reviews and reviews by category.

2022-12-09 10:49 UTC, captainread commented
Sort now works for Reviews and FilteredReviews, but in a very not "DRY" way. Tried to extract it into its own component and things got difficult. I want to work on the rest of my tickets first and if I have time I will come back to this! Thanks!!

2022-12-09 11:06 UTC, yalicee approved these changes
V happy with your code :)

2022-12-09 11:20 UTC, merged